# Generated by Django 4.1.7 on 2024-04-14 16:36

from django.db import migrations, models
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=150)),
                ("message", models.TextField()),
                ("answered", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name="ContactInfoText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=150)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=15, null=True, region=None
                    ),
                ),
                (
                    "address",
                    models.ManyToManyField(
                        related_name="address", to="contacts.contactinfotext"
                    ),
                ),
                (
                    "details",
                    models.ManyToManyField(
                        related_name="details", to="contacts.contactinfotext"
                    ),
                ),
                (
                    "working_hours",
                    models.ManyToManyField(
                        related_name="working_hours", to="contacts.contactinfotext"
                    ),
                ),
            ],
        ),
    ]
