# Generated by Django 4.1.7 on 2024-02-08 21:56

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfoText",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=150)),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True, max_length=15, null=True, region=None
                    ),
                ),
                (
                    "address",
                    models.ManyToManyField(
                        related_name="address", to="contacts.contactinfotext"
                    ),
                ),
                (
                    "details",
                    models.ManyToManyField(
                        related_name="details", to="contacts.contactinfotext"
                    ),
                ),
                (
                    "working_hours",
                    models.ManyToManyField(
                        related_name="working_hours", to="contacts.contactinfotext"
                    ),
                ),
            ],
        ),
    ]
