# Generated by Django 4.1.7 on 2024-02-04 12:45

from django.db import migrations, models
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="AddressBook",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Address"
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="City"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Postal Code",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Address"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="city",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="City"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=15,
                null=True,
                region=None,
                verbose_name="Phone number",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Postal Code"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="address_books",
            field=models.ManyToManyField(blank=True, null=True, to="users.addressbook"),
        ),
    ]
