# Generated by Django 4.1.7 on 2024-03-13 15:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_wishlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="wishlist",
            name="product",
        ),
    ]
