# Generated by Django 4.1.7 on 2024-03-16 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0008_product_sale"),
        ("users", "0004_remove_wishlist_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="wishlist",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="product.product",
            ),
        ),
    ]
