# Generated by Django 4.1.7 on 2024-03-17 16:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_wishlist_product"),
    ]

    operations = [
        migrations.AddField(
            model_name="addressbook",
            name="billing",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="addressbook",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
        migrations.AddField(
            model_name="addressbook",
            name="delivery",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="addressbook",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=15,
                null=True,
                region=None,
                verbose_name="Phone number",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="address_book_phone",
            field=phonenumber_field.modelfields.PhoneNumberField(
                blank=True,
                max_length=15,
                null=True,
                region=None,
                verbose_name="Address Phone number",
            ),
        ),
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "country",
                    django_countries.fields.CountryField(
                        blank=True, max_length=2, null=True
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        db_index=True,
                        max_length=254,
                        unique=True,
                        verbose_name="email address",
                    ),
                ),
                (
                    "phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        blank=True,
                        max_length=15,
                        null=True,
                        region=None,
                        verbose_name="Phone number",
                    ),
                ),
                (
                    "city",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="City"
                    ),
                ),
                (
                    "company_name",
                    models.CharField(
                        blank=True,
                        max_length=150,
                        null=True,
                        verbose_name="Company Name",
                    ),
                ),
                (
                    "vat",
                    models.CharField(
                        blank=True, max_length=150, null=True, verbose_name="VAT"
                    ),
                ),
                (
                    "address",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="Address"
                    ),
                ),
                (
                    "postal_code",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        null=True,
                        verbose_name="Postal Code",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
