# Generated by Django 4.1.7 on 2024-03-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_addressbook_billing_addressbook_country_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="company",
            name="sale_percent",
            field=models.FloatField(default=0.0),
        ),
    ]
