# Generated by Django 4.1.7 on 2024-04-01 16:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_company_sale_percent"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address_book_phone",
            field=models.CharField(
                blank=True,
                max_length=15,
                null=True,
                verbose_name="Address Phone number",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Phone number"
            ),
        ),
    ]
