# Generated by Django 4.1.7 on 2024-04-14 16:36

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Store",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("city", models.CharField(max_length=255)),
                ("country", django_countries.fields.CountryField(max_length=2)),
                ("postal_code", models.CharField(max_length=255)),
                ("phone_number", models.CharField(max_length=255)),
            ],
        ),
    ]
