# Generated by Django 4.1.7 on 2024-04-03 13:30

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("store", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="store",
            old_name="store_name",
            new_name="name",
        ),
        migrations.AlterField(
            model_name="store",
            name="country",
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
