version: "3.9"

services:
    api: &api
        build:
            context: .
            dockerfile: ./docker/production/django/Dockerfile
        command: /start
        image: floristika_backend
        volumes:
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        env_file:
            - ./.envs/.production/.django
            - ./.envs/.production/.postgres
        depends_on:
            - postgres
        networks:
            - reverseproxy_nw

    postgres:
        build:
            context: .
            dockerfile: ./docker/production/postgres/Dockerfile
        image: floristika_backend_database
        volumes:
            - production_postgres_data:/var/lib/postgresql/data
            - production_postgres_data_backups:/backups
        env_file:
            - ./.envs/.production/.postgres
        networks:
            - reverseproxy_nw

    nginx:
        restart: always
        depends_on:
            - api
        volumes:
            - static_volume:/app/staticfiles
            - media_volume:/app/mediafiles
        build:
            context: ./docker/production/nginx
            dockerfile: Dockerfile
        ports:
            - "8080:80"
        networks:
            - reverseproxy_nw

networks:
    reverseproxy_nw:

volumes:
    static_volume: {}
    media_volume: {}
    production_postgres_data: {}
    production_postgres_data_backups: {}