# Generated by Django 4.1.7 on 2024-04-14 16:36

import autoslug.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("text", "__first__"),
        ("image", "0001_initial"),
        ("filters", "0001_initial"),
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDescriptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
                ("text_en", models.TextField(null=True)),
                ("text_lv", models.TextField(null=True)),
                ("text_ru", models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="ProductDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                ("text", models.TextField()),
                ("text_en", models.TextField(null=True)),
                ("text_lv", models.TextField(null=True)),
                ("text_ru", models.TextField(null=True)),
                ("additional_text", models.TextField(blank=True, null=True)),
                ("additional_text_en", models.TextField(blank=True, null=True)),
                ("additional_text_lv", models.TextField(blank=True, null=True)),
                ("additional_text_ru", models.TextField(blank=True, null=True)),
                ("list", models.ManyToManyField(to="product.productdescriptionitem")),
            ],
        ),
        migrations.CreateModel(
            name="ProductDeliveryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("text", models.ManyToManyField(blank=True, null=True, to="text.text")),
            ],
        ),
        migrations.CreateModel(
            name="ProductDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "inside_delivery",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="inside",
                        to="product.productdeliveryitem",
                    ),
                ),
                (
                    "internal_delivery",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="internal",
                        to="product.productdeliveryitem",
                    ),
                ),
                (
                    "returns",
                    models.ManyToManyField(
                        blank=True,
                        null=True,
                        related_name="returns",
                        to="product.productdeliveryitem",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductCareInstruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                ("text", models.ManyToManyField(to="text.text")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("name_en", models.CharField(max_length=255, null=True)),
                ("name_lv", models.CharField(max_length=255, null=True)),
                ("name_ru", models.CharField(max_length=255, null=True)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        default="", editable=False, populate_from="name", unique=True
                    ),
                ),
                ("price", models.FloatField(default=0.0)),
                (
                    "price_for_authenticated",
                    models.FloatField(blank=True, default=0.0, null=True),
                ),
                (
                    "sale",
                    models.FloatField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MaxValueValidator(100.0),
                            django.core.validators.MinValueValidator(0.0),
                        ],
                    ),
                ),
                ("qty", models.PositiveIntegerField(default=0)),
                ("sold", models.PositiveIntegerField(default=0)),
                (
                    "rate",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MaxValueValidator(5.0),
                            django.core.validators.MinValueValidator(0.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("vendor_code", models.CharField(max_length=150)),
                (
                    "care",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="product.productcareinstruction",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="category.category",
                    ),
                ),
                (
                    "color",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="filters.color",
                    ),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="product.productdelivery",
                    ),
                ),
                (
                    "description",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="product.productdescription",
                    ),
                ),
                (
                    "images",
                    models.ManyToManyField(blank=True, null=True, to="image.image"),
                ),
                (
                    "size",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="filters.size",
                    ),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="category.subcategory",
                    ),
                ),
            ],
        ),
    ]
