# Generated by Django 4.1.7 on 2024-02-06 11:19

import autoslug.fields
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("category", "0001_initial"),
        ("image", "0001_initial"),
        ("filters", "0001_initial"),
        ("text", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductDescriptionItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("text", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="ProductDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                ("text", models.TextField()),
                ("additional_text", models.TextField(blank=True, null=True)),
                ("list", models.ManyToManyField(to="product.productdescriptionitem")),
            ],
        ),
        migrations.CreateModel(
            name="ProductDeliveryItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("text", models.ManyToManyField(blank=True, null=True, to="text.text")),
            ],
        ),
        migrations.CreateModel(
            name="ProductDelivery",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                (
                    "delivery_items",
                    models.ManyToManyField(
                        blank=True, null=True, to="product.productdeliveryitem"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductCareIntruction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                ("text", models.ManyToManyField(to="text.text")),
            ],
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        default="", editable=False, populate_from="name", unique=True
                    ),
                ),
                ("price", models.FloatField(default=0.0)),
                (
                    "price_for_auth",
                    models.FloatField(blank=True, editable=False, null=True),
                ),
                (
                    "sale_pecent",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MaxValueValidator(100.0),
                            django.core.validators.MinValueValidator(0.0),
                        ],
                    ),
                ),
                ("qty", models.PositiveIntegerField(default=0)),
                (
                    "rate",
                    models.FloatField(
                        default=0.0,
                        validators=[
                            django.core.validators.MaxValueValidator(5.0),
                            django.core.validators.MinValueValidator(0.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "care",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="product.productcareintruction",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="category.category",
                    ),
                ),
                (
                    "colors",
                    models.ManyToManyField(blank=True, null=True, to="filters.color"),
                ),
                (
                    "delivery",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="product.productdelivery",
                    ),
                ),
                (
                    "description",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="product.productdescription",
                    ),
                ),
                (
                    "images",
                    models.ManyToManyField(blank=True, null=True, to="image.image"),
                ),
                (
                    "sizes",
                    models.ManyToManyField(blank=True, null=True, to="filters.size"),
                ),
                (
                    "subcategory",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="category.subcategory",
                    ),
                ),
            ],
        ),
    ]
