# Generated by Django 4.1.7 on 2024-05-21 12:43

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="images",
        ),
    ]
