# Generated by Django 4.1.7 on 2024-03-06 15:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="artiqule",
            field=models.CharField(default="", max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="product",
            name="name_en",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name_lv",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="product",
            name="name_ru",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
