# Generated by Django 4.1.7 on 2024-03-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("text", "0001_initial"),
        ("product", "0002_product_artiqule_product_name_en_product_name_lv_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productdelivery",
            name="delivery_items",
        ),
        migrations.AddField(
            model_name="productcareintruction",
            name="text_en",
            field=models.ManyToManyField(null=True, to="text.text"),
        ),
        migrations.AddField(
            model_name="productcareintruction",
            name="text_lv",
            field=models.ManyToManyField(null=True, to="text.text"),
        ),
        migrations.AddField(
            model_name="productcareintruction",
            name="text_ru",
            field=models.ManyToManyField(null=True, to="text.text"),
        ),
        migrations.AddField(
            model_name="productdelivery",
            name="inside_delivery",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="inside",
                to="product.productdeliveryitem",
            ),
        ),
        migrations.AddField(
            model_name="productdelivery",
            name="internal_delivery",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="internal",
                to="product.productdeliveryitem",
            ),
        ),
        migrations.AddField(
            model_name="productdelivery",
            name="returns",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="returns",
                to="product.productdeliveryitem",
            ),
        ),
        migrations.AddField(
            model_name="productdescription",
            name="additional_text_en",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productdescription",
            name="additional_text_lv",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productdescription",
            name="additional_text_ru",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="productdescription",
            name="text_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="productdescription",
            name="text_lv",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="productdescription",
            name="text_ru",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="productdescriptionitem",
            name="text_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="productdescriptionitem",
            name="text_lv",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="productdescriptionitem",
            name="text_ru",
            field=models.TextField(null=True),
        ),
    ]
