# Generated by Django 4.1.7 on 2024-03-06 16:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("text", "0001_initial"),
        ("product", "0003_remove_productdelivery_delivery_items_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProductCareIntruction",
            new_name="ProductCareInstruction",
        ),
    ]
