# Generated by Django 4.1.7 on 2024-05-21 12:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0003_productimage_product_images"),
    ]

    operations = [
        migrations.AddField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="product.product",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="images",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="product_images",
                to="product.productimage",
            ),
        ),
    ]
