# Generated by Django 4.1.7 on 2024-03-06 16:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0004_rename_productcareintruction_productcareinstruction"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="sale_pecent",
            new_name="sale_percent",
        ),
    ]
