# Generated by Django 4.1.7 on 2024-07-03 17:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_product_vendor_code_public_alter_product_images"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price_for_authenticated",
        ),
    ]
