# Generated by Django 4.1.7 on 2024-03-06 17:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0005_rename_sale_pecent_product_sale_percent"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productcareinstruction",
            name="text_en",
        ),
        migrations.RemoveField(
            model_name="productcareinstruction",
            name="text_lv",
        ),
        migrations.RemoveField(
            model_name="productcareinstruction",
            name="text_ru",
        ),
    ]
