# Generated by Django 4.1.7 on 2024-03-06 21:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0006_remove_productcareinstruction_text_en_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sold",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
