# Generated by Django 4.1.7 on 2024-03-07 11:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0007_product_sold"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="sale",
            field=models.BooleanField(default=False),
        ),
    ]
