# Generated by Django 4.1.7 on 2024-04-01 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("filters", "0002_color_name_en_color_name_lv_color_name_ru_and_more"),
        ("product", "0008_product_sale"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product",
            old_name="artiqule",
            new_name="vendor_code",
        ),
        migrations.RemoveField(
            model_name="product",
            name="colors",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sizes",
        ),
        migrations.AddField(
            model_name="product",
            name="color",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="filters.color",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="filters.size",
            ),
        ),
    ]
