# Generated by Django 4.1.7 on 2024-04-04 15:05

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("product", "0009_rename_artiqule_product_vendor_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="price_for_auth",
        ),
    ]
