# Generated by Django 4.1.7 on 2024-04-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="authpercent",
            name="percent",
            field=models.FloatField(
                default=10.0, verbose_name="Percent for authenticated users."
            ),
        ),
    ]
