# Generated by Django 4.1.7 on 2024-04-01 18:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("filters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="color",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="color",
            name="name_lv",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="color",
            name="name_ru",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="size",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="size",
            name="name_lv",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="size",
            name="name_ru",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
