# Generated by Django 4.1.7 on 2024-03-25 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("image", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=100)),
                ("description_en", models.CharField(max_length=100, null=True)),
                ("description_lv", models.CharField(max_length=100, null=True)),
                ("description_ru", models.CharField(max_length=100, null=True)),
                ("description_code", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("works_from", models.DateTimeField(null=True)),
                ("works_to", models.DateTimeField(null=True)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="image.image",
                    ),
                ),
            ],
        ),
    ]
