# Generated by Django 4.1.7 on 2024-04-14 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("image", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Discount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "description",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "description_en",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "description_lv",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "description_ru",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("code", models.CharField(max_length=50, unique=True)),
                ("discount", models.FloatField(default=0.0)),
                ("works_from", models.DateTimeField(null=True)),
                ("works_to", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("intro", models.BooleanField(default=False)),
                (
                    "image",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="image.image",
                    ),
                ),
            ],
        ),
    ]
