# Generated by Django 4.1.7 on 2024-04-01 19:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0006_remove_order_discount_main"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("discount", "0002_rename_description_code_discount_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="discount",
            name="intro",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="discount",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="discount",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.DeleteModel(
            name="ExtraDiscount",
        ),
    ]
