# Generated by Django 4.1.7 on 2024-04-01 19:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0003_discount_intro_discount_user_alter_discount_code_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="description",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="discount",
            name="description_en",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="discount",
            name="description_lv",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="discount",
            name="description_ru",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
