# Generated by Django 4.1.7 on 2024-04-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0004_alter_discount_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="discount",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
