# Generated by Django 4.1.7 on 2024-04-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0005_alter_discount_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="discount",
            name="discount",
            field=models.FloatField(default=0.0),
        ),
    ]
