# Generated by Django 4.1.7 on 2024-07-03 16:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="image",
        ),
        migrations.RemoveField(
            model_name="category",
            name="image_best_sellers",
        ),
        migrations.RemoveField(
            model_name="category",
            name="image_new_in",
        ),
        migrations.RemoveField(
            model_name="category",
            name="image_sale",
        ),
    ]
