# Generated by Django 4.1.7 on 2024-03-06 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("category", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_lv",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="category",
            name="name_ru",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="name_en",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="name_lv",
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="subcategory",
            name="name_ru",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
