# Generated by Django 4.1.7 on 2024-03-18 20:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("image", "0001_initial"),
        (
            "category",
            "0002_category_name_en_category_name_lv_category_name_ru_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="image.image",
            ),
        ),
    ]
