# Generated by Django 4.1.7 on 2024-04-01 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("image", "0001_initial"),
        ("category", "0003_category_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image_best_sellers",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="best_sellers",
                to="image.image",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="image_new_in",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="new_in",
                to="image.image",
            ),
        ),
        migrations.AddField(
            model_name="category",
            name="image_sale",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="sale",
                to="image.image",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="all",
                to="image.image",
            ),
        ),
    ]
