# Generated by Django 4.1.7 on 2024-04-14 19:03

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "slug",
                    autoslug.fields.AutoSlugField(
                        editable=False, populate_from="name", unique=True
                    ),
                ),
                ("text", models.TextField()),
                ("text_en", models.TextField(null=True)),
                ("text_lv", models.TextField(null=True)),
                ("text_ru", models.TextField(null=True)),
            ],
        ),
    ]
