# Generated by Django 4.1.7 on 2024-03-06 16:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("text", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="text",
            name="text_en",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="text",
            name="text_lv",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="text",
            name="text_ru",
            field=models.TextField(null=True),
        ),
    ]
