# Generated by Django 4.1.7 on 2024-04-01 17:49

from django.db import migrations, models
import django.db.models.deletion
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("discount", "0002_rename_description_code_discount_code_and_more"),
        ("users", "0008_alter_user_address_book_phone_alter_user_phone"),
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shipping",
            name="zip_code",
        ),
        migrations.AddField(
            model_name="order",
            name="company_discount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="users.company",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="discount.discount",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="discount_main",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="discount.extradiscount",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="orders.shipping",
            ),
        ),
        migrations.AddField(
            model_name="shipping",
            name="postal_code",
            field=models.CharField(
                blank=True, max_length=120, null=True, verbose_name="Postal Code"
            ),
        ),
        migrations.AlterField(
            model_name="shipping",
            name="address",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Address"
            ),
        ),
        migrations.AlterField(
            model_name="shipping",
            name="city",
            field=models.CharField(
                blank=True, max_length=150, null=True, verbose_name="City"
            ),
        ),
        migrations.AlterField(
            model_name="shipping",
            name="country",
            field=django_countries.fields.CountryField(
                blank=True, max_length=2, null=True
            ),
        ),
        migrations.AlterField(
            model_name="shipping",
            name="phone",
            field=models.CharField(
                blank=True, max_length=15, null=True, verbose_name="Phone number"
            ),
        ),
    ]
