# Generated by Django 4.1.7 on 2024-04-01 18:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_remove_shipping_zip_code_order_company_discount_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_auth",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
