# Generated by Django 4.1.7 on 2024-05-21 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_orderorderitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="order",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="orders.order",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="items",
            field=models.ManyToManyField(
                related_name="order_items", to="orders.orderitem"
            ),
        ),
        migrations.DeleteModel(
            name="OrderOrderItem",
        ),
    ]
