# Generated by Django 4.1.7 on 2024-04-01 19:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0004_orderitem_guest_alter_orderitem_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="company_discount",
            new_name="company",
        ),
        migrations.AddField(
            model_name="order",
            name="auth_percent",
            field=models.IntegerField(default=0),
        ),
    ]
