# Generated by Django 4.1.7 on 2024-06-30 18:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_orderitem_order_alter_order_items_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="delivery_price",
            field=models.FloatField(default=0.0),
        ),
    ]
