# Generated by Django 4.1.7 on 2024-04-01 19:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0005_rename_company_discount_order_company_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="order",
            name="discount_main",
        ),
    ]
