# Generated by Django 4.1.7 on 2024-07-03 16:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_alter_order_total"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
