# Generated by Django 4.1.7 on 2024-04-01 20:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0007_billing_order_billing"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="order_created",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
