# Generated by Django 4.1.7 on 2024-07-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0008_alter_order_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="number",
            field=models.CharField(default="23558989", max_length=255),
        ),
    ]
