# Generated by Django 4.1.7 on 2024-04-03 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0009_order_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="billing",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.billing",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="orders.shipping",
            ),
        ),
    ]
