# Generated by Django 4.1.7 on 2024-04-04 20:00

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0010_alter_order_billing_alter_order_shipping"),
    ]

    operations = [
        migrations.CreateModel(
            name="BankDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("iban", models.CharField(max_length=255)),
                ("swift", models.CharField(max_length=255)),
                ("bank_name", models.CharField(max_length=255)),
                ("bank_address", models.CharField(max_length=255)),
                ("bank_city", models.CharField(max_length=255)),
                ("bank_country", django_countries.fields.CountryField(max_length=2)),
            ],
        ),
        migrations.AddField(
            model_name="order",
            name="invoice",
            field=models.FileField(blank=True, null=True, upload_to="invoices/"),
        ),
    ]
