# Generated by Django 4.1.7 on 2024-04-04 20:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_alter_user_address_book_phone_alter_user_phone"),
        ("store", "0002_rename_store_name_store_name_alter_store_country"),
        ("discount", "0004_alter_discount_description_and_more"),
        ("orders", "0011_bankdetails_order_invoice"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="store",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="store.store",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="company",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="users.company",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="discount",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="discount.discount",
            ),
        ),
    ]
