# Generated by Django 4.1.7 on 2024-07-03 17:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0012_alter_order_number"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="orderitem",
            name="price_for_authenticated",
        ),
    ]
