# Generated by Django 4.1.7 on 2024-04-04 20:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0012_order_store_alter_order_company_alter_order_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="invoice_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
