# Generated by Django 4.1.7 on 2024-04-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0013_order_invoice_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                    ("refunded    ", "Refunded"),
                    ("on-hold", "On Hold"),
                    ("completed", "Completed"),
                ],
                default="pending",
                max_length=255,
            ),
        ),
    ]
