# Generated by Django 4.1.7 on 2024-04-06 12:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0014_alter_order_status"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bankdetails",
            old_name="bank_address",
            new_name="lega_postal_code",
        ),
        migrations.RenameField(
            model_name="bankdetails",
            old_name="bank_city",
            new_name="legal_address",
        ),
        migrations.RenameField(
            model_name="bankdetails",
            old_name="bank_country",
            new_name="legal_country",
        ),
        migrations.AddField(
            model_name="bankdetails",
            name="legal_city",
            field=models.CharField(default="", max_length=255),
            preserve_default=False,
        ),
    ]
