# Generated by Django 4.1.7 on 2024-04-06 12:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0015_rename_bank_address_bankdetails_lega_postal_code_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bankdetails",
            old_name="lega_postal_code",
            new_name="legal_postal_code",
        ),
    ]
