# Generated by Django 4.1.7 on 2024-04-08 10:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0016_rename_lega_postal_code_bankdetails_legal_postal_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="company_total_auth",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
